[package]
name = "untitled2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
libavif-image = "0.11.0"
libavif = "0.12.0"
rayon = "1.8.0"
indicatif = "0.17.7"